## Solution for Day5 task
* Map the data from the file 'EmployeeData.csv' into a case class 
* Perform operations like filter,map ,reduce etc on the list of data

In [57]:
import scala.io
import scala.language.implicitConversions
// Define the case class
case class Employee(id:Int,name:String,city:String,salary:Int,department:String) //created the case class representing the entity

// implicit conversion from string to int
implicit def stringToInt(str: String): Int = Integer.parseInt(str)

// Function to read CSV file and map to case class -> specifically for converting salary into Integer from string
def readCSV(filePath: String): List[Employee] = {

    println("Reading file")
    val bufferedSource = io.Source.fromFile(filePath)//opens the file
    
    val employees = bufferedSource.getLines().drop(1).map { line => //gets the lines from the file 
        val cols = line.split(",").map(col=>col.trim())//splits the line and maps the column values into an array

        // println(cols(1))
        // println(cols.getClass.getSimpleName)
        Employee(cols(0),cols(1), cols(2), cols(3),cols(4))// initializes the Employee object with column values
    }.toList//gets the values into a list
    bufferedSource.close()
    employees
}
// // Get filename from user
// println("Please enter the filename:") ->Could have gotten the file path as user Input
// val filePath = scala.io.StdIn.readLine()
// Usage
// val filePath = "EmployeeData.csv"
val employeeData = readCSV(filePath)
// println(employeeData(0))
employeeData.foreach(println)//printing all the employees

//Filtering by salary and department->Salary>60000 and department=Engineering
val list1:List[Employee]=employeeData.filter(emp=>emp.salary>=60000 && emp.department.equals("Engineering"))
list1.foreach(println)//printing the filtered employees

//Using map operations to format output
list1.map(emp=>{
    s"Employee Details : id = ${emp.id}, name = ${emp.name}, city = ${emp.city}, salary = ${emp.salary}, department = ${emp.department}"
}).foreach(println)


//get the total salary of all the Engineering employees using .reduce

val totalEngSalary=list1.map(_.salary).reduce((a,b)=>a+b)
val averageEngSalary=totalEngSalary/list1.length

println(s"Total Engineering Salary = ${totalEngSalary}")

println(s"Average Engineering Salary = ${averageEngSalary}")

//Now  will try to save the departmental details mapped separately

case class DepartmentDetails(name:String,totalSalary:Int,averageSalary:Double)

//grouping the employees by their departments into a Map and then mapping the department details into a single DepartmentDetails Object
val departmentDetails = employeeData.groupBy(_.department).map { case (dept, employees) =>
    val totalSalary = employees.map(_.salary).sum
    val averageSalary = totalSalary.toDouble / employees.length
    DepartmentDetails(dept, totalSalary, averageSalary)
}.toList

//printing out the cumulative details for each department
departmentDetails.foreach(println)

Reading file
Employee(1,John Doe,New York,60000,Marketing)
Employee(2,Jane Smith,Los Angeles,55000,Finance)
Employee(3,Michael Johnson,Chicago,62000,HR)
Employee(4,Sarah Lee,San Francisco,58000,Engineering)
Employee(5,David Brown,Houston,63000,Operations)
Employee(6,Emily Taylor,Miami,54000,Sales)
Employee(7,James Wilson,Dallas,59000,Marketing)
Employee(8,Emma Anderson,Seattle,61000,Finance)
Employee(9,Matthew Martinez,Boston,57000,HR)
Employee(10,Olivia Thomas,Atlanta,64000,Engineering)
Employee(11,Liam Garcia,Denver,53000,Operations)
Employee(12,Sophia Hernandez,Phoenix,60000,Sales)
Employee(13,Alexander Lopez,Philadelphia,56000,Marketing)
Employee(14,Mia Gonzalez,Detroit,62000,Finance)
Employee(15,Ethan Perez,Minneapolis,55000,HR)
Employee(16,Isabella Carter,Portland,63000,Engineering)
Employee(17,Mason Torres,Baltimore,52000,Operations)
Employee(18,Ava Ramirez,San Diego,64000,Sales)
Employee(19,Logan Sanders,Washington,57000,Marketing)
Employee(20,Harper King,Birmingham,61000,Finance)
Employee(21,Lucas Rivera,Memphis,59000,HR)
Employee(22,Evelyn Scott,Nashville,60000,Engineering)
Employee(23,Avery Green,Milwaukee,56000,Operations)
Employee(24,Lincoln Taylor,Indianapolis,62000,Sales)
Employee(25,Sofia Cooper,Louisville,54000,Marketing)
Employee(26,Aiden Bennett,Jacksonville,63000,Finance)
Employee(27,Madison Flores,Charlotte,58000,HR)
Employee(28,Ella Collins,San Jose,65000,Engineering)
Employee(29,Chloe Howard,San Antonio,53000,Operations)
Employee(30,Carter Hughes,Oklahoma City,61000,Sales)
Employee(31,Aria Nelson,Tucson,57000,Marketing)
Employee(32,Grayson Baker,Cleveland,60000,Finance)
Employee(33,Zoey Morris,Mesa,55000,HR)
Employee(34,Nova Ward,Kansas City,64000,Engineering)
Employee(35,Hudson James,Virginia Beach,52000,Operations)
Employee(36,Leah Watson,Atlanta,62000,Sales)
Employee(37,Riley Brooks,Colorado Springs,54000,Marketing)
Employee(38,Emery Kelly,Raleigh,59000,Finance)
Employee(39,Luke Reed,Omaha,61000,HR)
Employee(40,Layla Cooper,Miami,56000,Engineering)
Employee(41,Ayden Rivera,Tulsa,63000,Operations)
Employee(42,Penelope Coleman,Oakland,58000,Sales)
Employee(43,Lincoln Powell,Minneapolis,65000,Marketing)
Employee(44,Aubrey Long,Arlington,60000,Finance)
Employee(45,Grace Hughes,Bakersfield,55000,HR)
Employee(46,Nolan Ward,Tampa,64000,Engineering)
Employee(47,Bella Barnes,Honolulu,52000,Operations)
Employee(48,Ellie Howard,Anaheim,62000,Sales)
Employee(49,Liam Wright,Pittsburgh,56000,Marketing)
Employee(50,Emma Evans,Cincinnati,61000,Finance)
Employee(10,Olivia Thomas,Atlanta,64000,Engineering)
Employee(16,Isabella Carter,Portland,63000,Engineering)
Employee(22,Evelyn Scott,Nashville,60000,Engineering)
Employee(28,Ella Collins,San Jose,65000,Engineering)
Employee(34,Nova Ward,Kansas City,64000,Engineering)
Employee(46,Nolan Ward,Tampa,64000,Engineering)
Employee Details : id = 10, name = Olivia Thomas, city = Atlanta, salary = 64000, department = Engineering
Employee Details : id = 16, name = Isabella Carter, city = Portland, salary = 63000, department = Engineering
Employee Details : id = 22, name = Evelyn Scott, city = Nashville, salary = 60000, department = Engineering
Employee Details : id = 28, name = Ella Collins, city = San Jose, salary = 65000, department = Engineering
Employee Details : id = 34, name = Nova Ward, city = Kansas City, salary = 64000, department = Engineering
Employee Details : id = 46, name = Nolan Ward, city = Tampa, salary = 64000, department = Engineering
Total Engineering Salary = 380000
Average Engineering Salary = 63333
DepartmentDetails(Engineering,494000,61750.0)
DepartmentDetails(Operations,444000,55500.0)
DepartmentDetails(Sales,483000,60375.0)
DepartmentDetails(Marketing,518000,57555.555555555555)
DepartmentDetails(HR,462000,57750.0)
DepartmentDetails(Finance,542000,60222.22222222222)

import scala.io
import scala.language.implicitConversions
defined class Employee
defined function stringToInt
defined function readCSV
employeeData: List[Employee] = List(
  Employee(
    id = 1,
    name = "John Doe",
    city = "New York",
    salary = 60000,
    department = "Marketing"
  ),
  Employee(
    id = 2,
    name = "Jane Smith",
    city = "Los Angeles",
    salary = 55000,
    department = "Finance"
  ),
  Employee(
    id = 3,
    name = "Michael Johnson",
    city = "Chicago",
    salary = 62000,
    department = "HR"
  ),
  Employee(
    id = 4,
    name = "Sarah Lee",
    city = "San Francisco",
    salary = 58000,
    department = "Engineering"
  ),
  Employee(
    id = 5,
    name = "David Brown",
    city = "Houston",
    salary = 63000,
    department = "Operations"
  ),
  Employee(
    id = 6,
    name = "Emily Taylor",
...
list1: List[Employee] = List(
  Employee(
    id = 10,
    name = "Olivia Thomas",
    city = "Atlanta",
    salary = 64000,
    department = "Engineering"
  ),
  Employee(
    id = 16,
    name = "Isabella Carter",
    city = "Portland",
    salary = 63000,
    department = "Engineering"
  ),
  Employee(
    id = 22,
    name = "Evelyn Scott",
    city = "Nashville",
    salary = 60000,
    department = "Engineering"
  ),
  Employee(
    id = 28,
    name = "Ella Collins",
    city = "San Jose",
    salary = 65000,
    department = "Engineering"
  ),
  Employee(
    id = 34,
    name = "Nova Ward",
    city = "Kansas City",
    salary = 64000,
    department = "Engineering"
  ),
  Employee(
    id = 46,
    name = "Nolan Ward",
...
totalEngSalary: Int = 380000
averageEngSalary: Int = 63333
defined class DepartmentDetails
departmentDetails: List[DepartmentDetails] = List(
  DepartmentDetails(
    name = "Engineering",
    totalSalary = 494000,
    averageSalary = 61750.0
  ),
  DepartmentDetails(
    name = "Operations",
    totalSalary = 444000,
    averageSalary = 55500.0
  ),
  DepartmentDetails(
    name = "Sales",
    totalSalary = 483000,
    averageSalary = 60375.0
  ),
  DepartmentDetails(
    name = "Marketing",
    totalSalary = 518000,
    averageSalary = 57555.555555555555
  ),
  DepartmentDetails(name = "HR", totalSalary = 462000, averageSalary = 57750.0),
  DepartmentDetails(
    name = "Finance",
    totalSalary = 542000,
    averageSalary = 60222.22222222222
  )
)